spring.application.name=fitnessGuidance
spring.datasource.url=jdbc:h2:file:./data/xiaolanshu;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

mybatis.configuration.map-underscore-to-camel-case=true

mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler
